### PR TITLE
Fix headers on README.md

### PR DESCRIPTION
**Pull request by huntermonk**

### CODE REVIEW

**Comment by wtmoose** [comment]
Doh! I'm pretty certain the existing readme used to render correctly. Thanks!

**Comment by huntermonk** [comment]
Haha I've noticed them a lot recently. Seems like recently GitHub [formalized their markdown spec](https://github.github.com/gfm/#atx-headings), could be that

**Comment by huntermonk** [comment]
Agreed

**Comment by wtmoose** [comment]
My sentiments exactly!

**Pull request merged**
